name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  unit-tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        node_version: [lts/-1, lts/*, latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - run: bun install --frozen-lockfile
      - run: bun --filter @psw-ui/cli lint
      - run: bun --filter @psw-ui/cli build
      - run: node packages/cli/bin/run.js --version
